[workspace]
resolver = "2"
members = [
  "contracts/*",
]


[workspace.package]
version = "0.1.0"
authors = ["Sun Zu Lab <contact@sunzulab.com>"]
license = "Apache-2.0"
edition = "2024"
homepage = "https://github.com/sunzu-lab/stellar-oracle-shield"
repository = "https://github.com/sunzu-lab/stellar-oracle-shield"

[workspace.dependencies]
soroban-sdk = "26"
stellar-oracle-shield-client = { path = "contracts/oracle-shield-client", version = "0.1.0" }
stellar-oracle-shield        = { path = "contracts/oracle-shield",        version = "0.1.0" }

[profile.release]
opt-level        = "z"
overflow-checks  = true
debug            = 0
strip            = "symbols"
debug-assertions = false
panic            = "abort"
codegen-units    = 1
lto              = true

# For more information about this profile see https://developers.stellar.org/docs/build/smart-contracts/example-contracts/logging#cargotoml-profile
[profile.release-with-logs]
inherits         = "release"
debug-assertions = true
