#!/bin/bash

## helper - deploy current built wasm with alias `oracle_shield`
##
## USAGE
##
##   deploy [NETWORK] SOURCE_ACCOUNT
##
##   NETWORK         any of testnet, mainnet and futurenet. Default, env STELLAR_NETWORK
##   SOURCE_ACCOUNT  any account identifier
##
## EXAMPLE
##
##   ./deploy alice

contract_name="stellar_oracle_shield"

network_param=""
case "$1" in
    testnet|mainnet|futurenet)
        network_param="--network $1"
        shift
        ;;
esac

source_account=${1}
if [ -z $source_account ]; then
    cat $0 | grep "^##" | sed -e "s/^##//"
    exit
fi

source_address=$(stellar keys address ${source_account})

echo "${source_account}[${source_address}] deploys ${contract_name}"

stellar contract deploy \
        --wasm target/wasm32v1-none/release/${contract_name}.wasm \
        --source-account ${source_account} \
        ${network_param} \
        --alias ${contract_name} \
        -- \
        --admin ${source_address}
