#!/bin/bash

## helper - invoke last deployed contract with alias `oracle_shield`
##
## USAGE
##
##   invoke [NETWORK] SOURCE_ACCOUNT FUNCTION PARAMETERS...
##
##   NETWORK         any of testnet, mainnet and futurenet. Default, env STELLAR_NETWORK
##   SOURCE_ACCOUNT  any account identifier
##
## EXAMPLE
##
##   ./invoke alice get_score --base CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA --quote CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC

contract_name="stellar_oracle_shield"

network_param=""
case "$1" in
    testnet|mainnet|futurenet)
        network_param="--network $1"
        shift
        ;;
esac

source_account=${1}
if [ -z $source_account ]; then
    cat $0 | grep "^##" | sed -e "s/^##//"
    exit
fi
source_address=$(stellar keys public-key ${source_account})
shift

echo "${source_account}[${source_address}] invoke ${contract_name}"

stellar contract invoke \
        --id ${contract_name} \
        --source-account ${source_account} \
        ${network_param} \
        -- \
        "$@"
