name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@e43b241f114bcf02151c30d61088506c6ad3ae0b # v25.1.0
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Stellar Oracle Shield Release'
      package: 'stellar-oracle-shield'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
