name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@v25.1.0
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Stellar Oracle Shield Release'
      package: 'stellar-oracle-shield'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
